version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db_volume:/var/lib/postgresql/data
  app:
    build: .
    environment:
      DB_USER: postgres
      DB_PASSWORD: password
      DB_HOST: db
    command: bash -c "rm -f tmp/pids/server.pid && bin/dev"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    depends_on:
      - db
volumes:
  db_volume:
